Repository ucsb-cs156/proj-frontiers, pull requests merged in 2025-08, with the labels that each got.

#287 pc - upgrade react-router
  .gitignore
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/main/components/Auth/SignInCard.js
  frontend/src/main/components/Courses/InstructorCoursesTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Nav/GithubLogin.js
  frontend/src/main/components/Nav/GoogleLogin.js
  frontend/src/main/components/RosterStudent/RosterStudentForm.js
  frontend/src/main/components/Users/RoleEmailForm.js
  frontend/src/main/pages/Admin/AdminsCreatePage.js
  frontend/src/main/pages/Admin/AdminsIndexPage.js
  frontend/src/main/pages/Admin/InstructorsCreatePage.js
  frontend/src/main/pages/Admin/InstructorsIndexPage.js
  frontend/src/main/pages/Auth/AccessDeniedPage.js
  frontend/src/main/pages/Auth/NotFoundPage.js
  frontend/src/main/pages/Auth/PromptSignInPage.js
  frontend/src/main/pages/Auth/SignInSuccessPage.js
  frontend/src/main/pages/HomePageConnectGithub.js
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/main/utils/currentUser.js
  frontend/src/setupTests.js
  frontend/src/stories/components/Common/OurPagination.stories.js
  frontend/src/tests/components/Common/OurPagination.test.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  frontend/src/tests/components/Courses/InstructorCoursesTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Nav/GithubLogin.test.js
  frontend/src/tests/components/Nav/GoogleLogin.test.js
  frontend/src/tests/components/RosterStudent/RosterStudentForm.test.js
  frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
  frontend/src/tests/components/Users/RoleEmailForm.test.js
  frontend/src/tests/components/Users/RoleEmailTable.test.js
  frontend/src/tests/pages/Admin/AdminUsersPage.test.js
  frontend/src/tests/pages/Admin/AdminsCreatePage.test.js
  frontend/src/tests/pages/Admin/AdminsIndexPage.test.js
  frontend/src/tests/pages/Admin/InstructorsCreatePage.test.js
  frontend/src/tests/pages/Admin/InstructorsIndexPage.test.js
  frontend/src/tests/pages/Admin/LoadingPage.test.js
  frontend/src/tests/pages/Auth/AccessDeniedPage.test.js
  frontend/src/tests/pages/Auth/NotFoundPage.test.js
  frontend/src/tests/pages/Auth/PromptSignInPage.test.js
  frontend/src/tests/pages/Auth/ProtectedPage.test.js
  frontend/src/tests/pages/Auth/SignInPage.test.js
  frontend/src/tests/pages/Auth/SignInSuccessPage.test.js
  frontend/src/tests/pages/HomePageConnectGithub.test.js
  frontend/src/tests/pages/HomePageLoggedIn.test.js
  frontend/src/tests/pages/HomePageLoggedOut.test.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
  frontend/src/tests/pages/Instructors/CoursesIndexPage.test.js
  frontend/src/tests/pages/ProfilePage.test.js
  frontend/src/tests/utils/currentUser.test.js
  frontend/src/tests/utils/systemInfo.test.js
  frontend/src/tests/utils/useBackend.test.js
Labels: M25, Dokku Deploy

#301 Customizing Permissions Level on Repos
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
  src/main/java/edu/ucsb/cs156/frontiers/enums/RepositoryPermissions.java
  src/main/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJob.java
  src/main/java/edu/ucsb/cs156/frontiers/services/RepositoryService.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJobTest.java
  src/test/java/edu/ucsb/cs156/frontiers/services/RepositoryServiceTests.java
Labels: M25, Ready for CR, Dokku Deploy

#257 Creating a Frontend for Posting Individual Student Repos
  frontend/src/main/components/Assignments/IndividualAssignmentForm.js
  frontend/src/main/components/TabComponent/AssignmentTabComponent.js
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/stories/components/Assignments/IndividualAssignmentForm.stories.js
  frontend/src/stories/pages/Instructor/InstructorCourseShowPage.stories.js
  frontend/src/tests/components/Assignments/IndividualAssignmentForm.test.js
  frontend/src/tests/components/TabComponent/AssignmentTabComponent.test.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
Labels: M25, Ready for CR, Dokku Deploy

#323 Adding a CSV download button
  frontend/src/App.js
  frontend/src/main/components/TabComponent/EnrollmentTabComponent.js
  frontend/src/main/pages/HomePageLoggedIn.js
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/tests/components/TabComponent/EnrollmentTabComponent.test.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
Labels: M25, Ready for CR, Dokku Deploy

#343 Disabling the Instructor Courses call without the Instructor Role
  frontend/src/main/pages/HomePageLoggedIn.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/pages/HomePageLoggedIn.test.js
  frontend/src/tests/utils/useBackend.test.js
Labels: M25, Ready for CR, Dokku Deploy

#345 divyanipunj - Improved UX on InstructorCoursesTable by updating tooltips and GitHub settings icon.
  frontend/src/main/components/Courses/InstructorCoursesTable.js
  frontend/src/tests/components/Courses/InstructorCoursesTable.test.js
Labels: M25, Dokku Deploy

#351 Narrowing the Scope of CustomErrorController
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CustomErrorController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CustomErrorControllerTests.java
Labels: M25, Ready for CR, Dokku Deploy

#334 Fill in Help / About page.
  frontend/src/fixtures/csvFixtures.js
  frontend/src/index.css
  frontend/src/main/pages/Help/HelpAboutPage.js
  frontend/src/main/pages/Help/HelpCsvPage.js
  frontend/src/stories/pages/Help/HelpAboutPage.stories.js
  frontend/src/stories/pages/Help/HelpCSVPage.stories.js
  frontend/src/tests/pages/Admin/AdminsIndexPage.test.js
  frontend/src/tests/pages/Help/HelpAboutPage.test.js
  frontend/src/tests/pages/Help/HelpCsvPage.test.js
Labels: M25, Ready for CR, Dokku Deploy

#380 pc - fix logic error in script for setting up application secret key on localhost
  keyconvert-localhost.sh
Labels: M25

#383 FERPA Security Pass
  src/main/java/edu/ucsb/cs156/frontiers/config/CourseSecurity.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/errors/CourseNotAuthorized.java
  src/test/java/edu/ucsb/cs156/frontiers/annotations/WithStaffCoursePermissions.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/security/CourseSecurityTests.java
  src/test/java/edu/ucsb/cs156/frontiers/security/DummyCourseSecurity.java
  src/test/java/edu/ucsb/cs156/frontiers/testconfig/TestCourseSecurity.java
Labels: M25, Ready for CR, Dokku Deploy

#388 Fixing FERPA annotations
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
Labels: M25, Ready for CR, Dokku Deploy

#384 divyanipunj - redirects to correct page after linking organization [DRAFT]
  frontend/src/main/components/Courses/InstructorCoursesTable.jsx
  frontend/src/main/pages/Auth/SignInSuccessPage.jsx
  frontend/src/tests/components/Courses/InstructorCoursesTable.test.jsx
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: Ready for CR, Dokku Deploy

#376 Ensuring Student Email and Student ID come from the same Roster Student
  docs/examples/egrades_with_duplicate_emails.csv
  docs/examples/egrades_with_duplicate_ids.csv
  docs/examples/egrades_with_email_and_student_ids_from_diff_students.csv
  frontend/src/fixtures/rosterStudentFixtures.js
  frontend/src/main/components/TabComponent/EnrollmentTabComponent.jsx
  frontend/src/stories/components/Courses/InstructorCoursesTable.stories.jsx
  frontend/src/tests/components/TabComponent/EnrollmentTabComponent.test.jsx
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: M25, Ready for CR, Dokku Deploy

#397 pc - update workflows for consistency with dining, and updated dependencies
  .github/workflows/01-gh-pages-pr-table.yml
  .github/workflows/02-gh-pages-rebuild-part-1.yml
  .github/workflows/04-gh-pages-redeploy-part-2.yml
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/15-backend-format.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
  .github/workflows/40-check-production-build.yml
  .github/workflows/41-integration.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
  .github/workflows/82-kanban-slack-update.yml
  .github/workflows/99-copy-issues.yml
Labels: M25

#389 Add support for Oregon State CSV format
  .github/workflows/02-gh-pages-rebuild-part-1.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/15-backend-format.yml
  docs/examples/OSU_CSV.csv
  frontend/src/fixtures/csvFixtures.js
  frontend/src/main/pages/Help/HelpCsvPage.jsx
  frontend/src/tests/pages/Help/HelpCsvPage.test.jsx
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsCSVController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/enums/InsertStatus.java
  src/main/java/edu/ucsb/cs156/frontiers/models/LoadResult.java
  src/main/java/edu/ucsb/cs156/frontiers/models/UpsertResponse.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsCSVControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: Ready for CR, Dokku Deploy, PRI1 - Must Complete

#429 Creating a Smoke Test
  .devcontainer/production/devcontainer.json
  .devcontainer/production/docker-compose.yml
  .github/workflows/42-smoke-test.yml
  Dockerfile
Labels: M25, Ready for CR
