Repository ucsb-cs156/proj-frontiers, pull requests merged in 2025-07, with the labels that each got.

#155 JOB - Async job that updates all student github org membership statuses
  src/main/java/edu/ucsb/cs156/frontiers/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJob.java
  src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerDetailedTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/JobsControllerJobsTests.java
  src/test/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJobTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java
Labels: M25

#145 FEATURE/BUG: admins can authorize GitHub apps
  frontend/src/App.js
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Courses/AdminCoursesTable.js
  frontend/src/main/components/Courses/InstructorCoursesTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Courses/CoursesIndexPage.js
  frontend/src/stories/components/Courses/AdminCoursesTable.stories.js
  frontend/src/stories/components/Courses/InstructorCoursesTable.stories.js
  frontend/src/tests/components/Courses/AdminCoursesTable.test.js
  frontend/src/tests/components/Courses/InstructorCoursesTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/CourseRepository.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTOTests.java
Labels: M25

#156 divyanipunj - Updating enum values for OrgStatus and updating the codebase accordingly [Issues #142, 163]
  frontend/src/fixtures/coursesFixtures.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/enums/OrgStatus.java
  src/main/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJob.java
  src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CSVDownloadsControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/jobs/CreateStudentRepositoriesJobTest.java
  src/test/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJobTests.java
  src/test/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTOTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/RosterStudentDTOServiceTests.java
Labels: M25

#188 Hotfix to Update OrgStatus from NONE to PENDING in the Prod/QA databases
  src/main/resources/db/migration/changes/011-Update-None-To-Pending.json
Labels: bug, M25, Ready for CR

#175 Marking Students as Owners Via Webhook
  src/main/java/edu/ucsb/cs156/frontiers/controllers/WebhookController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/WebhookControllerTests.java
Labels: M25

#183 FEATURE: instructor course show page
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/main/components/Courses/InstructorCoursesTable.js
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/stories/pages/Instructor/InstructorCourseShowPage.stories.js
  frontend/src/tests/components/Courses/InstructorCoursesTable.test.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: M25, Ready for CR

#178 REFACTOR: add a utility to isolate the hacks for email addresses
  src/main/java/edu/ucsb/cs156/frontiers/utilities/CanonicalFormConverter.java
  src/test/java/edu/ucsb/cs156/frontiers/utiltiies/CanonicalFormConverterTests.java
Labels: M25, Ready for CR

#174 pc - Add Index pages for Admins and Instructors
  frontend/src/App.js
  frontend/src/fixtures/roleEmailFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Users/RoleEmailTable.js
  frontend/src/main/pages/Admin/AdminUsersPage.js
  frontend/src/main/pages/Admin/AdminsIndexPage.js
  frontend/src/main/pages/Admin/InstructorsIndexPage.js
  frontend/src/main/pages/Instructors/CoursesIndexPage.js
  frontend/src/main/utils/RoleEmailUtils.js
  frontend/src/stories/components/Users/RoleEmailTable.stories.js
  frontend/src/stories/pages/Admin/AdminsIndexPage.stories.js
  frontend/src/stories/pages/Admin/InstructorsIndexPage.stories.js
  frontend/src/tests/components/Users/RoleEmailTable.test.js
  frontend/src/tests/pages/Admin/AdminUsersPage.test.js
  frontend/src/tests/pages/Admin/AdminsIndexPage.test.js
  frontend/src/tests/pages/Admin/InstructorsIndexPage.test.js
  frontend/src/tests/pages/Instructors/CoursesIndexPage.test.js
  frontend/src/tests/utils/roleEmail.test.js
  src/main/java/edu/ucsb/cs156/frontiers/controllers/AdminsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/AdminsControllerTests.java
Labels: M25, Ready for CR

#176 Appropriately Marking Students as Invited in MembershipAuditJob
  src/main/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJob.java
  src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
  src/test/java/edu/ucsb/cs156/frontiers/jobs/MembershipAuditJobTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java
Labels: M25

#186 pc - rewrite scripts and instructions for converting the private key for the Github app
  .env.SAMPLE
  .gitignore
  docs/github-app-setup-dokku.md
  docs/github-app-setup-localhost.md
  keyconvert-localhost.sh
  keyconvert.sh
Labels: M25, Ready for CR

#166 Factoring Out Course Permissions Management
  src/main/java/edu/ucsb/cs156/frontiers/config/CourseSecurity.java
  src/main/java/edu/ucsb/cs156/frontiers/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
  src/test/java/edu/ucsb/cs156/frontiers/ControllerTestCase.java
  src/test/java/edu/ucsb/cs156/frontiers/annotations/WithInstructorCoursePermissions.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/security/CourseSecurityTests.java
  src/test/java/edu/ucsb/cs156/frontiers/security/DummyCourseSecurity.java
  src/test/java/edu/ucsb/cs156/frontiers/testconfig/TestCourseSecurity.java
Labels: M25

#200 divyanipunj - Changed all instances of HomePage to HomePageLoggedOut.
  frontend/src/App.js
  frontend/src/main/pages/HomePageLoggedOut.js
  frontend/src/stories/pages/HomePageLoggedOut.stories.js
  frontend/src/tests/pages/HomePageLoggedOut.test.js
Labels: M25, Ready for CR

#185 FEATURE - add roster student table to instructor course show page
  frontend/src/fixtures/rosterStudentFixtures.js
  frontend/src/main/components/RosterStudent/RosterStudentTable.js
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/main/utils/rosterStudentUtils.js
  frontend/src/stories/components/RosterStudent/RosterStudentTable.stories.js
  frontend/src/stories/pages/Instructor/InstructorCourseShowPage.stories.js
  frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
  frontend/src/tests/utils/rosterStudentUtils.test.js
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: M25, Ready for CR

#199 Creating a Modal to Create and Edit Courses
  frontend/src/main/components/Courses/CourseModal.js
  frontend/src/stories/components/Courses/CourseModal.stories.js
  frontend/src/tests/components/Courses/CourseModal.test.js
Labels: M25, Ready for CR

#202 Improving Integration Test Speed
  pom.xml
Labels: M25, Ready for CR

#198 Refactoring the Frontend Current User Structure
  frontend/src/App.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/main/pages/Instructors/CoursesIndexPage.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/main/utils/currentUser.js
  frontend/src/tests/utils/currentUser.test.js
Labels: M25, Ready for CR

#203 Adding a Service to Delete a Frontiers Installation
  src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationLinkerService.java
  src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationLinkerServiceTests.java
Labels: M25, Ready for CR

#204 FEATURE: As an admin, I can delete a course, BACKEND only.
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: M25, Ready for CR

#171 Adding Azure Active Directory as a Sign-On
  pom.xml
  src/main/java/edu/ucsb/cs156/frontiers/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/frontiers/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/frontiers/services/GoogleSignInServiceImpl.java
  src/main/java/edu/ucsb/cs156/frontiers/services/SystemInfoServiceImpl.java
  src/main/java/edu/ucsb/cs156/frontiers/startup/AzureProfileEnabler.java
  src/main/resources/META-INF/spring.factories
  src/main/resources/application-microsoft.properties
  src/test/java/edu/ucsb/cs156/frontiers/services/SystemInfoServiceImplTests.java
Labels: M25

#219 Creating a Confirmation Modal
  frontend/src/main/components/Common/ConfirmationModal.js
  frontend/src/stories/components/Common/ConfirmationModal.stories.js
  frontend/src/tests/components/Common/ConfirmationModal.test.js
Labels: M25, Ready for CR

#209 Database Rewrite
  src/main/java/edu/ucsb/cs156/frontiers/entities/CourseStaff.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/User.java
  src/main/resources/db/migration/changes/000-init-database.json
  src/main/resources/db/migration/changes/001-create-Course.json
  src/main/resources/db/migration/changes/002-create-CourseStaff.json
  src/main/resources/db/migration/changes/003-create-Jobs.json
  src/main/resources/db/migration/changes/004-create-RosterStudent.json
  src/main/resources/db/migration/changes/005-create-Users.json
  src/main/resources/db/migration/changes/006-RosterStudent-add-github-fields.json
  src/main/resources/db/migration/changes/007-create-Instructors.json
  src/main/resources/db/migration/changes/008-CourseStaff-add-staff-fields.json
  src/main/resources/db/migration/changes/008-create-Admins.json
  src/main/resources/db/migration/changes/009-Add-Family-Names.json
  src/main/resources/db/migration/changes/010-drop-admin-and-instructor-from-users.json
  src/main/resources/db/migration/changes/011-Update-None-To-Pending.json
Labels: M25, Ready for CR

#218 Handling Not Found on the CourseShowPage
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
  frontend/src/tests/utils/useBackend.test.js
Labels: M25, Ready for CR

#216 Adding a Sign In Card for Use on the Sign In Page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main/components/Auth/SignInCard.js
  frontend/src/stories/components/Auth/SignInCard.stories.js
  frontend/src/tests/components/Auth/SignInCard.test.js
Labels: M25, Ready for CR

#217 Adding a full sign-in page
  frontend/src/App.js
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Nav/GoogleLogin.js
  frontend/src/main/pages/Auth/SignInPage.js
  frontend/src/stories/pages/Auth/SignInPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Nav/GoogleLogin.test.js
  frontend/src/tests/pages/Auth/SignInPage.test.js
Labels: M25

#213 Checking Organization Status on Invite Fail
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java
Labels: M25, Ready for CR

#230 dj - fixed member inference to say member rather than direct_member
  src/main/java/edu/ucsb/cs156/frontiers/services/GoogleSignInServiceImpl.java
  src/main/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberService.java
  src/test/java/edu/ucsb/cs156/frontiers/services/OrganizationMemberServiceTests.java
Labels: M25, Ready for CR

#233 Adding backend disconnect for GitHub accounts
  src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/frontiers/controllers/GithubControllerTests.java
Labels: M25, Ready for CR

#231 FEATURE (BACKEND) - Proof of concept for GraphQL queries to Github (look up default branch name)
  pom.xml
  src/main/java/edu/ucsb/cs156/frontiers/config/GithubGraphQLClientConfig.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLController.java
  src/main/java/edu/ucsb/cs156/frontiers/errors/CourseNotAuthorized.java
  src/main/java/edu/ucsb/cs156/frontiers/services/GithubGraphQLService.java
  src/test/java/edu/ucsb/cs156/frontiers/config/GithubGraphQLClientConfigTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/ApiControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/GithubGraphQLControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/GithubGraphQLServiceTests.java
Labels: M25, Ready for CR

#247 pc - put course title at top of page above the tabs on InstructorCourseShowPage
  frontend/src/main/pages/Instructor/InstructorCourseShowPage.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
Labels: M25, Ready for CR

#251 divyanipunj - Added HomePageConnectGithub Component and Updated Related Files
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/HomePageConnectGithub.js
  frontend/src/main/pages/LoadingPage.js
  frontend/src/stories/pages/HomePageConnectGithub.stories.js
  frontend/src/stories/pages/HomePageLoggedIn.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Nav/GithubLogin.test.js
  frontend/src/tests/pages/HomePageConnectGithub.test.js
Labels: M25, Ready for CR

#258 Loosening the Assignment Repo Permissions
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RepositoryController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RepositoryControllerTests.java
Labels: M25

#249 pc - update OurTable to use latest version of TanStack React Table
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/fixtures/ourTableFixtures.js
  frontend/src/main/components/Common/SortCaret.js
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/main/components/Courses/InstructorCoursesTable.js
  frontend/src/main/components/OurTable.js
  frontend/src/main/components/RosterStudent/RosterStudentTable.js
  frontend/src/main/components/Users/RoleEmailTable.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/utils/rosterStudentUtils.js
  frontend/src/stories/components/OurTable.stories.js
  frontend/src/stories/components/Users/RoleEmailTable.stories.js
  frontend/src/tests/components/Common/SortCarets.test.js
  frontend/src/tests/components/Courses/InstructorCoursesTable.test.js
  frontend/src/tests/components/OurTable.test.js
  frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
  frontend/src/tests/utils/rosterStudentUtils.test.js
Labels: M25, Ready for CR, Dokku Deploy

#260 [HOTFIX] de-duping package-lock
  frontend/package-lock.json
Labels: M25, Ready for CR, Dokku Deploy

#259 Adding Staff Webhooks
  src/main/java/edu/ucsb/cs156/frontiers/controllers/WebhookController.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/CourseStaffRepository.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/WebhookControllerTests.java
Labels: M25, Ready for CR, Dokku Deploy

#263 Adding Instructors to the Users Table
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/stories/components/Users/UsersTable.stories.js
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: M25, Ready for CR, Dokku Deploy

#261 Paginating the Users Table (One Consolidated PR)
  frontend/src/main/components/Common/OurPagination.js
  frontend/src/main/pages/Admin/AdminUsersPage.js
  frontend/src/stories/components/Common/OurPagination.stories.js
  frontend/src/stories/pages/Admin/AdminUsersPage.stories.js
  frontend/src/tests/components/Common/OurPagination.test.js
  frontend/src/tests/pages/Admin/AdminUsersPage.test.js
  src/main/java/edu/ucsb/cs156/frontiers/FrontiersMain.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/UserRepository.java
  src/main/java/edu/ucsb/cs156/frontiers/services/UserDataDTOService.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/services/UserDataDTOServiceTests.java
Labels: M25, Ready for CR, Dokku Deploy

#275 Version Bump to TanStack Query v5
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.js
  frontend/src/main/pages/HomePageLoggedIn.js
  frontend/src/main/utils/currentUser.js
  frontend/src/main/utils/systemInfo.js
  frontend/src/main/utils/useBackend.js
  frontend/src/stories/pages/HomePageLoggedIn.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Nav/GithubLogin.test.js
  frontend/src/tests/components/Nav/GoogleLogin.test.js
  frontend/src/tests/components/RosterStudent/RosterStudentForm.test.js
  frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
  frontend/src/tests/components/Users/RoleEmailForm.test.js
  frontend/src/tests/components/Users/RoleEmailTable.test.js
  frontend/src/tests/pages/Admin/AdminUsersPage.test.js
  frontend/src/tests/pages/Admin/AdminsCreatePage.test.js
  frontend/src/tests/pages/Admin/AdminsIndexPage.test.js
  frontend/src/tests/pages/Admin/InstructorsCreatePage.test.js
  frontend/src/tests/pages/Admin/InstructorsIndexPage.test.js
  frontend/src/tests/pages/Admin/LoadingPage.test.js
  frontend/src/tests/pages/Auth/SignInPage.test.js
  frontend/src/tests/pages/Auth/SignInSuccessPage.test.js
  frontend/src/tests/pages/HomePageConnectGithub.test.js
  frontend/src/tests/pages/HomePageLoggedIn.test.js
  frontend/src/tests/pages/HomePageLoggedOut.test.js
  frontend/src/tests/pages/Instructor/InstructorCourseShowPage.test.js
  frontend/src/tests/pages/Instructors/CoursesIndexPage.test.js
  frontend/src/tests/pages/ProfilePage.test.js
  frontend/src/tests/utils/currentUser.test.js
  frontend/src/tests/utils/systemInfo.test.js
  frontend/src/tests/utils/useBackend.test.js
Labels: M25, Ready for CR, Dokku Deploy

#276 Enforcing Internal React Router Navigation
  frontend/src/main/components/Courses/InstructorCoursesTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Admin/AdminsIndexPage.js
  frontend/src/main/pages/Admin/InstructorsIndexPage.js
Labels: M25, Ready for CR, Dokku Deploy
